### ISSUE TITLE
[bug] Notification Whitelist

### ISSUE THREAD

**Issue by zerebos** [deathbyprograms/BetterDiscordAddons#1]
For your notification whitelist plugin you do a webpack search on every single notification at line 222 https://github.com/deathbyprograms/BetterDiscordAddons/blob/3633e3ea3a776ab76dffa8777b9904d4bf3ccfd9/dist/NotificationWhitelist/NotificationWhitelist.plugin.js#L222

These searches do not automatically cache results so it is performing a long search on every notification. For users with medium to high end devices this will not matter too much. But for lower end devices, these delays can be noticeable especially when multiple notifications occur in quick succession. Please cache the result of the search earlier on in the plugin.

**Comment by deathbyprograms** [comment]
I believe it should be fixed with 16a3209

**Comment by zerebos** [comment]
That's one way to do it yeah
